<a href="https://colab.research.google.com/github/Lovejits/myfirstrepo/blob/main/pandas_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas

In [2]:
df = pandas.read_csv("salaries_by_college_major.csv")

In [7]:
df.shape

(51, 6)

In [5]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [8]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [9]:
df.dropna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [10]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [11]:
df.dropna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [3]:
df_nna = df.dropna()

In [13]:
df_nna.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [14]:
df_nna["Starting Median Salary"]

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [15]:
df_nna["Starting Median Salary"].max()

74300.0

In [16]:
df_nna["Starting Median Salary"].idxmax()

43

In [17]:
df_nna["Undergraduate Major"].loc[43]

'Physician Assistant'

In [18]:
df_nna.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [20]:
df_nna.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [21]:
df_nna["Mid-Career Median Salary"].max()

107000.0

In [22]:
df_nna["Mid-Career Median Salary"].idxmax()

8

In [23]:
df_nna.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [24]:
df_nna["Starting Median Salary"].min()

34000.0

In [25]:
df_nna["Starting Median Salary"].idxmin()

49

In [26]:
df_nna["Undergraduate Major"].loc[49]

'Spanish'

In [27]:
df_nna["Mid-Career Median Salary"].idxmin()

18

In [28]:
df_nna["Mid-Career Median Salary"].min()

52000.0

In [29]:
df_nna["Undergraduate Major"].loc[18]

'Education'

In [4]:
df_nna["Mid-Career 90th Percentile Salary"] - df_nna["Mid-Career 10th Percentile Salary"]

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [6]:
df_nna["Mid-Career 90th Percentile Salary"]

0     152000.0
1     161000.0
2     150000.0
3     138000.0
4     136000.0
5     125000.0
6     135000.0
7     147000.0
8     194000.0
9     148000.0
10    148000.0
11    143000.0
12    162000.0
13    154000.0
14    171000.0
15    107000.0
16    153000.0
17    210000.0
18    102000.0
19    168000.0
20    133000.0
21    136000.0
22    195000.0
23    111000.0
24    132000.0
25    156000.0
26    112000.0
27    101000.0
28    149000.0
29    124000.0
30    173000.0
31    129000.0
32    107000.0
33    157000.0
34    145000.0
35    146000.0
36    175000.0
37    183000.0
38    163000.0
39    134000.0
40     98300.0
41     99200.0
42    168000.0
43    124000.0
44    178000.0
45    168000.0
46    127000.0
47     96400.0
48    118000.0
49     96400.0
Name: Mid-Career 90th Percentile Salary, dtype: float64

In [7]:
df_nna["Mid-Career 90th Percentile Salary"].subtract(df_nna["Mid-Career 10th Percentile Salary"])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [8]:
spread_col = df_nna["Mid-Career 90th Percentile Salary"] - df_nna["Mid-Career 10th Percentile Salary"]

In [9]:
df_nna.insert(1, 'Spread', spread_col)

In [10]:
df_nna.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [11]:
df_nna['Spread'].idxmin()

40

In [12]:
df_nna.loc[40]

Undergraduate Major                   Nursing
Spread                                50700.0
Starting Median Salary                54200.0
Mid-Career Median Salary              67000.0
Mid-Career 10th Percentile Salary     47600.0
Mid-Career 90th Percentile Salary     98300.0
Group                                Business
Name: 40, dtype: object

In [13]:
df_nna.sort_values('Mid-Career 90th Percentile Salary')

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business

In [14]:
sorted = df_nna.sort_values('Mid-Career 90th Percentile Salary')

In [15]:
sorted[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].tail()

     Undergraduate Major  Mid-Career 90th Percentile Salary
44               Physics                           178000.0
37                  Math                           183000.0
8   Chemical Engineering                           194000.0
22               Finance                           195000.0
17             Economics                           210000.0

In [16]:
df_nna.sort_values('Mid-Career 90th Percentile Salary', ascending=False)

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS

In [17]:
sorted = df_nna.sort_values('Mid-Career 90th Percentile Salary', ascending=False)

In [18]:
sorted[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [19]:
spread_diff = df_nna.sort_values('Spread', ascending=False)

In [20]:
sorted[['Undergraduate Major', 'Spread']].head()

     Undergraduate Major    Spread
17             Economics  159400.0
22               Finance  147800.0
8   Chemical Engineering  122100.0
37                  Math  137800.0
44               Physics  122000.0